"""Added comment/subreddit/thread schema and edit to Subreddit model

Revision ID: 2266bff54277
Revises: ecdd239f06e5
Create Date: 2021-12-08 16:40:40.816141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2266bff54277'
down_revision = 'ecdd239f06e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subreddits', 'content_about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subreddits', 'content_about',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
