"""updated subreddit schema

Revision ID: 854d6d918810
Revises: 8f1baa994954
Create Date: 2021-12-09 18:18:57.155000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854d6d918810'
down_revision = '8f1baa994954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('description', sa.String(length=1000), nullable=False))
    op.drop_column('subreddits', 'content_about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('content_about', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('subreddits', 'description')
    # ### end Alembic commands ###
