"""Added Thread, Comment and Subreddit it Tables

Revision ID: cb7e76f826d9
Revises: a58558da0f61
Create Date: 2021-12-07 11:46:26.152950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7e76f826d9'
down_revision = 'a58558da0f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('content_about', sa.String(length=1000), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('thread_owner', sa.Integer(), nullable=True),
    sa.Column('parent_subreddit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_subreddit'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['thread_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('parent_thread', sa.Integer(), nullable=True),
    sa.Column('comment_owner', sa.Integer(), nullable=True),
    sa.Column('parent_comment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['parent_thread'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'date_created')
    op.drop_table('comments')
    op.drop_table('threads')
    op.drop_table('subreddits')
    # ### end Alembic commands ###
